ALTER TABLE "MerchProduct" ADD COLUMN IF NOT EXISTS "yourCost" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MerchProduct" ADD COLUMN IF NOT EXISTS "weightGrams" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MerchProduct" ADD COLUMN IF NOT EXISTS "productType" TEXT;
ALTER TABLE "MerchProduct" ADD COLUMN IF NOT EXISTS "countryOfOrigin" TEXT;
ALTER TABLE "MerchProduct" ADD COLUMN IF NOT EXISTS "cusmaCertified" BOOLEAN NOT NULL DEFAULT false;
