ALTER TABLE "MerchProduct" ADD COLUMN IF NOT EXISTS "cost" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "costAtPurchase" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "productSlug" TEXT;
